sudo: required
matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - sourceline: 'ppa:george-edison55/cmake-3.x'
          packages:
            - clang-5.0
            - ninja-build
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

language: cpp
before_install:
    - eval "${MATRIX_EVAL}"
    - chmod +x travis.sh
    - ./travis.sh
script: cmake -GNinja -H. -Bbuild && cmake --build build
