matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

language: cpp
before_install:
    - eval "${MATRIX_EVAL}"
script: cmake -GNinja -H. -Bbuild && cmake --build build
