#ifndef DRIVER_H
#define DRIVER_H


#include "parsing/lexer.h"
#include "ast/ASTBaseNode.h"
//Autogenerated
#include "parser.hh"
#include <vector>

namespace Ni {

class Driver {
public:
	Driver();
	~Driver();
	int parse();
	void AddToList(ASTNode *ptr);
	void SwitchStream(std::istream *is);
	void DumpModule();	

	friend class Parser;
	friend class Lexer;
private:
	Lexer lexer;
	Parser parser;
	Visitor visitor;
	std::vector<ASTNode*> ast;
};

}

#endif
