#ifndef DRIVER_H
#define DRIVER_H


#include "parsing/lexer.h"
#include "ast/ASTBaseNode.h"
//Autogenerated
#include "parser.hh"
#include <vector>

namespace Ni {

class Driver {
public:
	Driver();
	~Driver();
	int parse();
	void SwitchStream(std::istream *is, std::string* filename);
	void DumpModule();	

	friend class Parser;
	friend class Lexer;
private:
	ASTNode* addNode(ASTNode* node) {ast.push_back(node); return node; }
	void setColumn(unsigned int col);
	void setLine(unsigned int line);
	Lexer lexer;
	Parser parser;
	Visitor visitor;
	std::string* filename;
	std::vector<ASTNode*> ast;
	unsigned int col;
	unsigned int line;
};

}

#endif
